authdb:
  extends:
    file: pwd/docker-services.yml
    service: authdb
  volumes:
    - ./data/authdb:/bitnami/mariadb/data

prismdb:
  image: bitnami/mariadb:10.1.13-r0
  volumes:
    - ./data/prismdb:/bitnami/mariadb/data
  environment:
    - MARIADB_USER=prismdb
    - MARIADB_DATABASE=prismdb
    - MARIADB_PASSWORD=prismdb

pwd:
  extends:
    file: pwd/docker-services.yml
    service: pwd
  links:
    - authdb:authdb

server:
  extends:
    file: docker-service.yml
    service: server
  links:
    - authdb:authdb
    - prismdb:prismdb