authdb:
  extends:
    file: web/pwd/docker-services.yml
    service: authdb
  volumes:
    - ./data/authdb:/bitnami/mariadb

prismdb:
  image: bitnami/mariadb:10.1.13-r0
  volumes:
    - ./data/prismdb:/bitnami/mariadb
  environment:
    - MARIADB_USER=prismdb
    - MARIADB_DATABASE=prismdb
    - MARIADB_PASSWORD=prismdb

pwd:
  extends:
    file: web/pwd/docker-services.yml
    service: pwd
  links:
    - authdb:authdb

server:
  extends:
    file: docker-service.yml
    service: server
  volumes:
    - ./web/wait-for-it.sh:/wait:ro
  command: /wait -s -t 120 authdb:3306 -- /start
  links:
    - authdb:authdb
    - prismdb:prismdb