authdb:
  extends:
    file: pwd/docker-services.yml
    service: authdb
  volumes:
    - ./data/authdb:/bitnami/mariadb/data

pwd:
  extends:
    file: pwd/docker-services.yml
    service: pwd
  links:
    - authdb:authdb

server:
  image: itzg/minecraft-server:latest
  environment:
    # System
    - TYPE=SPIGOT
    - VERSION=1.8.8
    - JVM_OPTS=-Xmx1024M -Xms1024M
    - VIEW_DISTANCE=10

    # Sever
    - EULA=TRUE
    - OPS=admin
    - MOTD=My Mincraft Server

    # World
    - HARDCORE=false
    - MODE=survival
    - DIFFICULTY=hard
    - LEVEL_TYPE=DEFAULT
    - MAX_PLAYERS=10
    - MAX_WORLD_SIZE=10000
    - MAX_BUILD_HEIGHT=256
    - PVP=false
    - GENERATE_STRUCTURES=true
    - SPAWN_ANIMALS=true
    - SPAWN_MONSTERS=true
    - SPAWN_NPCS=true

    # To know other Environment variables,
    # please visit https://github.com/itzg/dockerfiles/tree/master/minecraft-server

  links:
    - authdb:authdb
  ports:
    - "25565:25565"
    - "8123:8123"
  volumes:
    - ./data/server:/data
    - ./plugins:/data/plugins
  tty: true
  stdin_open: true