db:
  image: bitnami/mariadb
  environment:
    - MARIADB_USER=authme
    - MARIADB_PASSWORD=au
    - MARIADB_DATABASE=authme
  volumes:
    - ./db:/bitnami/mariadb/data

server:
  image: itzg/minecraft-server:latest
  environment:
    - EULA=TRUE
    - TYPE=SPIGOT
    - VERSION=1.8.8
    - DIFFICULTY=hard
    - OPS=fntsrswl
    - MOTD=OOLab Server
  links:
    - db:mariadb
  ports:
    - "25565:25565"
    - "8123:8123"
  volumes:
    - ./server:/data
    - ./plugins:/data/plugins
  tty: true
  stdin_open: true

pwd:
  build: ./pwd
  links:
      - db:mariadb
  ports:
    - "8000:80"
  volumes:
    - "./:/var/www/html/"
  environment:
    - WEBSITE_TITLE=麥塊帳號管理網站 - Minecraft PWD Utility
